_BASE_: "Base-DiffusionDet.yaml"
MODEL:
  META_ARCHITECTURE: 'FSDiffusionDet'
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  DiffusionDet:
    NUM_PROPOSALS: 200
    NUM_CLASSES: 20
DATASETS:
  TRAIN: ("DIOR_train2017",)
  VAL: ("DIOR_val2017",)
  TEST:  ("DIOR_test2017",)
SOLVER:
  STEPS: (99000,)
  MAX_ITER: 100000
  # MAX_ITER: 20
  CHECKPOINT_PERIOD: 10000
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
  MIN_SIZE_TRAIN: (512,)
  MAX_SIZE_TRAIN: 512
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 512
TRAIN_MODE: 'regular'
FINETUNE:
  MAX_ITER: 130000
TEST:
  EVAL_PERIOD: 500
# OUTPUT_DIR: 'runs/05-01-2023_14:21:54'
