_BASE_: "../Base-DiffusionDet.yaml"
MODEL:
  META_ARCHITECTURE: 'FSDiffusionDet'
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  DiffusionDet:
    NUM_PROPOSALS: 500
    NUM_CLASSES: 20
DATASETS:
  TRAIN: ("DIOR_train",)
  VAL: ("DIOR_val",)
  TEST:  ("DIOR_test",)
SOLVER:
  IMS_PER_BATCH: 16
  MAX_ITER: 0
  STEPS: (4000,)
  # MAX_ITER: 20
  CHECKPOINT_PERIOD: 10000
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
  MIN_SIZE_TRAIN: (512,)
  MAX_SIZE_TRAIN: 512
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 512
# TRAIN_MODE: 'support_attention'
TRAIN_MODE: 'simplefs'
FINETUNE:
  MAX_ITER: 5000
TEST:
  EVAL_PERIOD: 500
# OUTPUT_DIR: 'runs/23-01-2023_17:23:02'
# OUTPUT_DIR: 'runs/07-02-2023_17:34:01'
FEWSHOT:
  ATTENTION:
    EXTRACT_EVERY: 10
    MAX_NUM_CLASSES: 3
  K_SHOT: 10
  N_WAYS_TEST: 5
  N_WAYS_TRAIN: 5
  BASE_SUPPORT: 'rng'

