_BASE_: "../Base-DiffusionDet.yaml"
MODEL:
  META_ARCHITECTURE: 'FSDiffusionDet'
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  DiffusionDet:
    NUM_PROPOSALS: 200
    NUM_CLASSES: 16
DATASETS:
  TRAIN: ("COCO_train2017",)
  VAL: ("COCO_val2017",)
  TEST:  ("COCO_val2017",)
SOLVER:
  STEPS: (40000,)
  MAX_ITER: 10
  # MAX_ITER: 20
  CHECKPOINT_PERIOD: 10000
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
# TRAIN_MODE: 'support_attention'
TRAIN_MODE: 'simplefs'
FINETUNE:
  MAX_ITER: 25
TEST:
  EVAL_PERIOD: 500
# OUTPUT_DIR: 'runs/23-01-2023_17:23:02'
# OUTPUT_DIR: 'runs/07-02-2023_17:34:01'
FEWSHOT:
  ATTENTION:
    EXTRACT_EVERY: 10
    MAX_NUM_CLASSES: 3
  K_SHOT: 10
  BASE_SUPPORT: 'rng'

