_BASE_: "../Base-DiffusionDet.yaml"
PREVENT_WEIGHTS_LOADING: False
MODEL:
  # BACKBONE:
  #   NAME: 'build_resnet_dino_fpn_backbone'
  META_ARCHITECTURE: 'FSDiffusionDet'
  # WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  # WEIGHTS: "detectron2://dino_resnet50_pretrain.pth"
  WEIGHTS: "/home/pierre/Documents/PHD/FSDiffusionDet/runs/Backbones/model_base_COCO_500P_BS16_2G/model_base_COCO_500P_BS16_2G.pth"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  DiffusionDet:
    NUM_PROPOSALS: 500
    NUM_CLASSES: 16
DATASETS:
  TRAIN: ("DOTA_train2017",)
  VAL: ("DOTA_val2017",)
  TEST:  ("DOTA_test2017",)
SOLVER:
  IMS_PER_BATCH: 12 
  STEPS: (4000,)
  MAX_ITER: 0
  # MAX_ITER: 20
  CHECKPOINT_PERIOD: 10000
  # LR_SCHEDULER_NAME: 'WarmupCosineLR'
  BASE_LR: 1e-4
  # BASE_LR_END: 1e-5
  # WARMUP_ITERS: 500
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
  MIN_SIZE_TRAIN: (512,)
  MAX_SIZE_TRAIN: 512
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 512
# TRAIN_MODE: 'support_attention'
TRAIN_MODE: 'simplefs'
FINETUNE:
  CROSS_DOMAIN: True
  MAX_ITER: 5000
  MODEL_FREEZING:
    BACKBONE_AT: 0
    BACKBONE_MODE: 'all'
    MODULES: ['backbone']
    HEAD_ALL: True
TEST:
  EVAL_PERIOD: 500
# OUTPUT_DIR: 'runs/23-01-2023_17:23:02'
# OUTPUT_DIR: 'runs/07-02-2023_17:34:01'
FEWSHOT:
  SPLIT_METHOD: 'all_novel'
  N_WAYS_TRAIN: 16
  N_WAYS_TEST: 16
  ATTENTION:
    EXTRACT_EVERY: 10
    MAX_NUM_CLASSES: 3
  K_SHOT: 10
  BASE_SUPPORT: 'rng'

