_BASE_: "Base-DiffusionDet.yaml"
MODEL:
  META_ARCHITECTURE: 'FSDiffusionDet'
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  DiffusionDet:
    NUM_PROPOSALS: 200
    NUM_CLASSES: 16
DATASETS:
  TRAIN: ("DOTA_train2017",)
  VAL: ("DOTA_val2017",)
  TEST:  ("DOTA_test2017",)
SOLVER:
  STEPS: (99000,)
  MAX_ITER: 10000
  # MAX_ITER: 20
  CHECKPOINT_PERIOD: 10000
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
  MIN_SIZE_TRAIN: (512,)
  MAX_SIZE_TRAIN: 512
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 512
TRAIN_MODE: 'simplefs'
FINETUNE:
  MAX_ITER: 15000
TEST:
  EVAL_PERIOD: 500
# OUTPUT_DIR: 'runs/19-01-2023_09:24:07'
FEWSHOT:
  ATTENTION:
    EXTRACT_EVERY: 1
  K_SHOT: 10
  BASE_SUPPORT: 'rng'

