_BASE_: "Base-DiffusionDet.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  DiffusionDet:
    NUM_PROPOSALS: 200
    NUM_CLASSES: 16
DATASETS:
  TRAIN: ("DOTA_train2017",)
  VAL: ("DOTA_val2017",)
  TEST:  ("DOTA_test2017",)
SOLVER:
  STEPS: (130000, 145000)
  MAX_ITER: 150000
  # MAX_ITER: 20
  CHECKPOINT_PERIOD: 10000
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
  MIN_SIZE_TRAIN: (512,)
  MAX_SIZE_TRAIN: 512
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 512
TRAIN_MODE: 'regular'
